### ISSUE TITLE
Creatures with haste from Battlecry can't move without help.

### ISSUE THREAD

**Issue by jollki** [davewx7/citadel#145] opened 2017-10-29 03:39 UTC
A newly summoned creature that receives haste from Battlecry won't get an opportunity to move unless another creature is able to move.  Here's a relevant test case.
>https://pastebin.com/NBvAxxq6

Summon a Green Adder and cast Battlecry (in either order). The adder won't animate to indicate unused movement points and the the advancement button will still say "End Turn." Summon a Savage Wolf and move it by clicking directly or pressing the move button and the snake will realize that it can move.

**Comment by galegosimpatico** [comment] 2017-11-02 09:20
Can't reproduce. My guess is that @davewx7 fixed it already.

Can you @jollki follow up to confirm if it is fixed for you now or it is me that am failing to reproduce?

You are welcome to join the [Argentum Age Discord server](https://discord.gg/0s6mSoZ1vJPlvcIw) if you already have not.

**Comment by sapientN3T** [comment] 2017-11-02 15:34
Just a quick note that I was able to observe the buggy behavior in a recent game. I had two freshly summoned units and cast battlecry. Only one of them got animated to indicate unused movement points. The other (a Rokh) did not. However when I click Move they both moved as expected.

**Comment by galegosimpatico** [comment] 2017-11-02 15:57
@sapientN3T happened to me too. Recently. Maybe twice. I didn't write it down because the unit moved, but it wasn't showing the move intention animation.

**Comment by jollki** [comment] 2017-11-02 16:58
Bug appears to be fixed.  It was very reproducible for me and now everything works as expected.

**Comment by galegosimpatico** [comment] 2017-11-02 23:52
@sapientN3T I think https://github.com/davewx7/citadel/issues/145#issuecomment-341460629 is a different issue, I'm sure it is still there in `master` as I am writing, I think it is straightforward to reproduce, I think I can fix it and probably without breaking something else.

If you are not already trying, I advice you to try to fix it yourself.

If you don't already know why, when you are done you are going to know why.

**Comment by sapientN3T** [comment] 2018-06-25 17:04
Fixed by https://github.com/davewx7/citadel/commit/8c721eb90114d5491b1196175f3c689ddd701f4b

**Closed by sapientN3T** 2018-06-25 17:04 UTC
