### ISSUE TITLE
Assertion failed knife in the dark card played

### ISSUE THREAD

**Issue by huwjenjinn** [davewx7/citadel#241] opened 2018-08-08 08:51 UTC
Played the **knife in the dark card** against a damaged (2 hits remained) **warrior elite** which was on a **mine** card. Game crashed with Assertion failed

> `formula_vm.cpp:455 ASSERTION FAILED: Assertion failed: entry=null or (entry.creature and not entry.creature.is_land) at in VIrtual Machine: At modules/citadel/data/classes/crypt.cfg 112: ...ntry.creature and not entry.creature.is_land)`
`.......................................................^`

I have a screen shot of the ---VM: output if that's of help?
_Ignore the dots preceding the circumflex only there to push the pointer underneath "is_land"_

**Comment by galegosimpatico** [comment] 2018-08-08 09:59
> [...]
> I have a screen shot of the ---VM: output if that's of help?
> [...]

Yes! I think it could be very helpful. It could help a possible association to any of issues 176 or 188.

**Comment by mandeville-school** [comment] 2018-08-08 10:09
Here it is:

![screenshot from 2018-08-08 09-48-53](https://user-images.githubusercontent.com/10206921/43831270-771e7fec-9afb-11e8-8b9c-45828a461382.png)

**Comment by huwjenjinn** [comment] 2018-08-08 11:26
Just had another error in the same vein when I played the **Royal **Guard**** into my summoning area which already had a mine placed.

![screenshot from 2018-08-08 12-24-00](https://user-images.githubusercontent.com/10206921/43834489-2fadcf36-9b06-11e8-9839-23ba6b214a54.png)
![screenshot from 2018-08-08 12-23-52](https://user-images.githubusercontent.com/10206921/43834491-31d07958-9b06-11e8-91e0-d63215192bc8.png)

**Comment by galegosimpatico** [comment] 2018-08-08 11:37
> [...]
> 
> Definitely looks like the same issue as 176 imo.

Not at all sure. 176 reports "stuck". That "stuck" suggests _server_ crash (1vsAI games are played against some type of AI server locally executed). When the local server of a 1vsAI game crash, the client application stays infinitely waiting for an answer that won't come.

An assertion error at the client (with subsequent client exit) suggests a probably different root cause.

Could you please confirm that you were using the self-updating client for this, using game data controlled by the self-updating client (1.0.683)? Or, in case you were using a Git controlled version for either [the engine](https://github.com/anura-engine/anura/) or [the game itself](https://github.com/davewx7/citadel/), could you type the revs/commits you were using?

> Just had another error in the same vein when I played the Royal Guard into my summoning area which already had a mine placed.
> 
> [...]

Definitely interesting, thanks.

**Comment by galegosimpatico** [comment] 2018-08-08 11:39
> Just had another error in the same vein when I played the Royal Guard into my summoning area which already had a mine placed.
> 
> [...]

Hopefully this would make it easier to reproduce and fix.

**Comment by galegosimpatico** [comment] 2018-08-08 14:39
I tried to reproduce, but I don't get it. :cry:

It could be 1.0.683, judging `data/classes/crypt.cfg:112`.

**Comment by huwjenjinn** [comment] 2018-08-08 14:57
Hi again, thanks for looking.

My version was downloaded directly from the website here:
http://theargentlark.com/files/argentum-age.tar.bz2

It then updated itself (created an **aa** folder) and when run reports version number 1.0.683 as you picked up from the crypt.cfg file
![screenshot from 2018-08-08 15-54-40](https://user-images.githubusercontent.com/10206921/43845342-b2917700-9b23-11e8-9c25-0f1d4a873f34.png)

**Comment by huwjenjinn** [comment] 2018-08-08 17:57
Okay, have a complete logfile of a single game where this error occurred. See the attached log of the game I took from the console output. Note that the AI was playing the cards at the time of error in a campaign scenario.

[argentumAge.log](https://github.com/davewx7/citadel/files/2271335/argentumAge.log)

**Comment by galegosimpatico** [comment] 2018-08-08 19:11
Thanks again! I don't know how to reverse engineer a game out of console output. 🙁

There's also such thing as a server log (`server-log.txt`), which records log from the local server for 1vsAI games, but gets rewritten each game. I don't know how to read that log either, but it can help the other developers.

Finally there are actual multiplayer matches, where some of the bugs might be easier to understand, and some others might be harder to understand. Multiplayer games are unequivocally identifiable by their sequence number, which you can find somewhere in the player info widget present at the main and sp/mp lobbies.

Hope you enjoy the game very much. 🏰⏳📜🌳👼🔪

**Comment by huwjenjinn** [comment] 2018-08-09 10:35
I'll post up that server-log.txt as soon as I can then.
I'll also try and get a multiplayer match-up to produce the same message and post up what I can here.

As for the game, it's been excellent fun so thanks to all involved.

**Comment by huwjenjinn** [comment] 2018-08-09 15:17
Not sure of the cause this time but another assertion error as above. This time I have the server log file (my naming convention as keeping unique copies of the `server-log.txt` just in case they are useful)
[server-log1808091556.log](https://github.com/davewx7/citadel/files/2274711/server-log1808091556.log)

**Comment by galegosimpatico** [comment] 2018-08-09 15:44
> [...] This time I have the server log file [...]

Here I'm sure to see both decks, so that's definitely something.

The whole game movements are _probably_ logged, so that would be helpful. I can't replay a game out of this in a nice automated way, but that's probably feasible for the future.

I guess for many bugs just reading the last movements would be enough. But maybe hardest bugs could be found only by investigating full logs like this.

**Comment by sapientN3T** [comment] 2018-09-20 06:14
After reviewing the log file, this appears to be a duplicate of bug #218.

@huwjenjinn please confirm if your version of /data/classes/creature.cfg was missing this line `	if(attacker.is_land, inflict_damage(game, damage),` which should be at around line number 351, at the beginning of function `inflict_combat_damage`?


You may want to apply patch https://github.com/davewx7/citadel/commit/cabb65fcb935471e7e746e97b94b56b75732cdfb
to the file data/classes/creature.cfg

While you are doing that, I suggest you also apply patch
https://github.com/davewx7/citadel/commit/b9ab76ff3202812d18a8a80181eefa470009a233
to the file data/classes/game_state.cfg


@galegosimpatico  I am not familiar with the distribution mechanisms, but I hope that somehow these fixes can be pushed to all the users. Thanks.

**Comment by galegosimpatico** [comment] 2018-10-20 22:28
@sapientN3T marked this as [duplicate](https://github.com/davewx7/citadel/labels/duplicate) of https://github.com/davewx7/citadel/issues/218, which was closed by him, the patch being distributed in [1.0.684](https://github.com/davewx7/citadel/milestone/1), so we can close.

**Closed by galegosimpatico** 2018-10-20 22:28 UTC
Labels: bug, duplicate
