### ISSUE TITLE
Clicking »recent games« in offline mode crashes

### ISSUE THREAD

**Issue by adrianheine** [davewx7/citadel#103] opened 2016-11-08 19:42 UTC
anura/anura-engine@23483b5ae3b7b94ee320b9e6610c9da7fd1e56ce, 04a67dd588fa65c94058d38e4933a233e38cf149

```
CRITICAL: formula_vm.cpp:421 ASSERTION FAILED: Assertion failed: Type mis-match. Expected object found null at in Virtual Machine: At modules/citadel/data/objects/title_controller.cfg 49:
tbs_send(object<- mm_client, { type: 'get_recent_games', user: username });
         ^

---VM:
   0: OP_CONSTANT 0 ( "@eval (UNSERIALIZABLE_OBJECT N12_GLOBAL__N_117tbs_send_functionE)" )
   2: OP_LOOKUP 203
   4: OP_DUP
   5: OP_CONSTANT 1 ( "@eval (UNSERIALIZABLE_OBJECT N12_GLOBAL__N_119variant_type_simpleE)" )
   7: OP_IS
   8: OP_POP_JMP_IF 6 ( -> 15)
   10: OP_CONSTANT 2 ( "Type mis-match. Expected object found " )
   12: OP_SWAP
   13: OP(+)
-->14: OP_ASSERT
   15: OP_CONSTANT 3 ( "type" )
   17: OP_CONSTANT 4 ( "get_recent_games" )
   19: OP_CONSTANT 5 ( "user" )
   21: OP_LOOKUP 216
   23: OP_PUSH_INT 4
   25: OP_MAP
   26: OP_CALL_BUILTIN 2

---STACK---
  --TOS+0--
'Type mis-match. Expected object found null'
  --TOS+1--
(0x55ac77546560){Uninspectable Object: object}


CRITICAL: At modules/citadel/data/objects/title_controller.cfg 49:
tbs_send(object<- mm_client, { type: 'get_recent_games', user: username });
^-------------------------------------------------------------------------^

At modules/citadel/data/objects/player_profile_pane.cfg 179:
if(n = 0, title_controller.show_recent_games());
^----------------------------------------------^

At modules/gui/data/objects/combo_label_controller.cfg 32:
[
^

At modules/gui/data/objects/combo_label.cfg 77:
[
^


---
CRITICAL: stack trace:
CRITICAL:   ./anura : formula_vm::VirtualMachine::executeInternal(game_logic::FormulaCallable const&, std::vector<ffl::IntrusivePtr<game_logic::FormulaCallable>, std::allocator<ffl::IntrusivePtr<game_logic::FormulaCallable> > >&, std::vector<variant, std::allocator<variant> >&, short const*, short const*) const+0xf7d
CRITICAL:   ./anura : formula_vm::VirtualMachine::execute(game_logic::FormulaCallable const&) const+0x74
CRITICAL:   ./anura : ()+0xe1344d
CRITICAL:   ./anura : ()+0xe31054
CRITICAL:   ./anura : game_logic::FormulaExpression::evaluate(game_logic::FormulaCallable const&) const+0x2e
CRITICAL:   ./anura : ()+0xf2ffe8
CRITICAL:   ./anura : ()+0xf30121
CRITICAL:   ./anura : game_logic::Formula::execute(game_logic::FormulaCallable const&) const+0x95
CRITICAL:   ./anura : variant::operator()(std::vector<variant, std::allocator<variant> > const&) const+0xfab
CRITICAL:   ./anura : formula_vm::VirtualMachine::executeInternal(game_logic::FormulaCallable const&, std::vector<ffl::IntrusivePtr<game_logic::FormulaCallable>, std::allocator<ffl::IntrusivePtr<game_logic::FormulaCallable> > >&, std::vector<variant, std::allocator<variant> >&, short const*, short const*) const+0x19de
CRITICAL:   ./anura : formula_vm::VirtualMachine::execute(game_logic::FormulaCallable const&) const+0x74
CRITICAL:   ./anura : ()+0xe1344d
CRITICAL:   ./anura : ()+0xe31054
CRITICAL:   ./anura : game_logic::Formula::execute(game_logic::FormulaCallable const&) const+0x95
CRITICAL:   ./anura : variant::operator()(std::vector<variant, std::allocator<variant> > const&) const+0xfab
CRITICAL:   ./anura : formula_vm::VirtualMachine::executeInternal(game_logic::FormulaCallable const&, std::vector<ffl::IntrusivePtr<game_logic::FormulaCallable>, std::allocator<ffl::IntrusivePtr<game_logic::FormulaCallable> > >&, std::vector<variant, std::allocator<variant> >&, short const*, short const*) const+0x19de
CRITICAL:   ./anura : formula_vm::VirtualMachine::execute(game_logic::FormulaCallable const&) const+0x74
CRITICAL:   ./anura : ()+0xe1344d
CRITICAL:   ./anura : game_logic::Formula::execute(game_logic::FormulaCallable const&) const+0x95
CRITICAL:   ./anura : variant::operator()(std::vector<variant, std::allocator<variant> > const&) const+0xfab
CRITICAL:   ./anura : formula_vm::VirtualMachine::executeInternal(game_logic::FormulaCallable const&, std::vector<ffl::IntrusivePtr<game_logic::FormulaCallable>, std::allocator<ffl::IntrusivePtr<game_logic::FormulaCallable> > >&, std::vector<variant, std::allocator<variant> >&, short const*, short const*) const+0x19de
CRITICAL:   ./anura : formula_vm::VirtualMachine::execute(game_logic::FormulaCallable const&) const+0x74
CRITICAL:   ./anura : ()+0xe1344d
CRITICAL:   ./anura : game_logic::Formula::execute(game_logic::FormulaCallable const&) const+0x95
CRITICAL:   ./anura : CustomObject::handleEventInternal(int, game_logic::FormulaCallable const*, bool)+0x2b5
CRITICAL:   ./anura : CustomObject::handleEvent(int, game_logic::FormulaCallable const*)+0x17d
CRITICAL:   ./anura : LevelRunner::handle_mouse_events(SDL_Event const&)+0x1285
CRITICAL:   ./anura : LevelRunner::play_cycle()+0x3523
CRITICAL:   ./anura : LevelRunner::play_level()+0x82
CRITICAL:   ./anura : main()+0x860a
CRITICAL:   /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main()+0xf1
CRITICAL:   ./anura : _start()+0x2a
CRITICAL: ---
```

**Comment by galegosimpatico** [comment] 2018-03-31 16:50
Can't reproduce now. Very likely to have been fixed by a8462e45c7ac7afc972e87b952f69e10d3cdde92.

**Closed by galegosimpatico** 2018-03-31 16:50 UTC
