### ISSUE TITLE
"Assertion Failed" on Windows 10

### ISSUE THREAD

**Issue by Lucius4** [davewx7/citadel#218] opened 2018-06-03 09:17 UTC
I got this error during normal game against computer and similar when playing in the multiplayer mode.

![obraz](https://user-images.githubusercontent.com/5897458/40885049-9f4ccf74-671f-11e8-8339-9b30bfe97ca2.png)

**Comment by sapientN3T** [comment] 2018-06-03 13:06
Thanks for this report, but it is very difficult to investigate without the game-log.txt. Please include the game-log and the server-log with all future bug reports.

**Comment by Lucius4** [comment] 2018-06-03 13:19
I hope it helps more.

[game-log.txt](https://github.com/davewx7/citadel/files/2065977/game-log.txt)
[server-log.txt](https://github.com/davewx7/citadel/files/2065978/server-log.txt)

**Comment by sapientN3T** [comment] 2018-06-03 16:40
hi @Lucius4 unfortunately those files did not contain the error, because you restarted the game so it overwrote the files. 

However, based on my hunch that it was related to Oldric's Trap, I was able to reproduce it.

The problem is that when the creature code wants to fire on_kill, it does a lookup of the creature that killed it, get_creature_by_summon_id. however that is incorrect since it might have been killed by a land. it should call get_permanent_by_summon_id. so this assert detected a pre-existing code error.
the land that kills in this case is Oldric's Trap.

That means that cards which rely on killed_by_this_turn to grant an effect to the killer (i.e. Yogi, Bounty, Heir to the Throne) need to consider that the killer might be a land!
alternatively, maybe Oldric's Trap should just use inflict_damage instead of inflict_combat_damage

In the end, I decided that the simplest fix was to prevent lands from registering as the 'attacker', so it should be fixed now.

**Closed by sapientN3T** 2018-06-03 16:40 UTC
